apiVersion: v1
kind: Service
metadata:
  name: java-svc
spec:
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 8080  #service port
    targetPort: 8080 # application port
  type: NodePort
